# Generated by Django 6.0.6 on 2026-06-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sx_co', '0001_initial'),
    ]

    operations = [
    ]
